trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  bashvar: 'Demo'

steps:
- script: echo $(bashvar)
  displayName: 'About'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
#- task: DotNetCoreCLI@2
#  displayName: 'dotnet build'
#  inputs:
#    projects: '**/*.csproj'
#    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    arguments: '--no-build --configuration $(BuildConfiguration) --output $(Build.StagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- bash: echo "Build Done!"
  displayName: 'Proceeding to release'

